/* THE COUNTING BOARD's examples (rhythm-dojo/counting.html), one per line: every case of Mr. Graham's counting.
   rhythm = the text format of shared/counting.js; expect = the counting in plain text, where ^( ) marks the SMALL raised
   syllables (underlined) and ( ) around a group marks a rest. The automatic tests check every line, so a change to the
   counting rule that breaks one of these fails the tests. Add examples freely. */
window.RD_EXAMPLES = [
  {name: 'Quarter notes', time: '4/4', rhythm: 'q q q q', expect: '1 2 3 4'},
  {name: 'Half notes', time: '4/4', rhythm: 'h h', expect: '1^(2) 3^(4)'},
  {name: 'Half note on beat 3', time: '4/4', rhythm: 'q q h', expect: '1 2 3^(4)'},
  {name: 'Dotted half note', time: '4/4', rhythm: 'h. q', expect: '1^(2 3) 4'},
  {name: 'Whole note', time: '4/4', rhythm: 'w', expect: '1^(2 3 4)'},
  {name: 'Quarter rest on beat 2', time: '4/4', rhythm: 'q qr q q', expect: '1 (2) 3 4'},
  {name: 'Half rest on beat 3', time: '4/4', rhythm: 'q q hr', expect: '1 2 (3^(4))'},
  {name: 'Half rest on beat 1', time: '4/4', rhythm: 'hr h', expect: '(1^(2)) 3^(4)'},
  {name: 'Whole rest', time: '4/4', rhythm: 'wr', expect: '(1^(2 3 4))'},
  {name: 'Dotted half rest', time: '4/4', rhythm: 'h.r q', expect: '(1^(2 3)) 4'},
  {name: 'Eighth-note pairs', time: '4/4', rhythm: 'e e e e e e e e', expect: '1 & 2 & 3 & 4 &'},
  {name: 'Eighths and quarters', time: '4/4', rhythm: 'e e q e e q', expect: '1 & 2 3 & 4'},
  {name: 'Eighth rest on the &', time: '4/4', rhythm: 'e er q q q', expect: '1 (&) 2 3 4'},
  {name: 'Eighth rests on the beat', time: '4/4', rhythm: 'er e er e q q', expect: '(1) & (2) & 3 4'},
  {name: 'Quarter rests and eighths', time: '4/4', rhythm: 'qr e e qr e e', expect: '(1) 2 & (3) 4 &'},
  {name: 'Dotted quarter + eighth', time: '4/4', rhythm: 'q. e q q', expect: '1^(& 2) & 3 4'},
  {name: 'Dotted quarter on beat 3', time: '4/4', rhythm: 'q q q. e', expect: '1 2 3^(& 4) &'},
  {name: 'Syncopation: eighth, quarter, eighth', time: '4/4', rhythm: 'e q e q q', expect: '1 &^(2) & 3 4'},
  {name: 'Syncopation all the way', time: '4/4', rhythm: 'e q q q e', expect: '1 &^(2) &^(3) &^(4) &'},
  {name: 'Syncopation after a rest', time: '4/4', rhythm: 'er q e q. e', expect: '(1) &^(2) & 3^(& 4) &'},
  {name: 'Four sixteenths', time: '4/4', rhythm: 's s s s q h', expect: '1 e & a 2 3^(4)'},
  {name: 'Eighth + two sixteenths', time: '4/4', rhythm: 'e s s e s s h', expect: '1 & a 2 & a 3^(4)'},
  {name: 'Two sixteenths + eighth', time: '4/4', rhythm: 's s e s s e h', expect: '1 e & 2 e & 3^(4)'},
  {name: 'Sixteenths mixed', time: '4/4', rhythm: 's s e e s s q q', expect: '1 e & 2 & a 3 4'},
  {name: 'Sixteenth rest', time: '4/4', rhythm: 'sr s s s q h', expect: '(1) e & a 2 3^(4)'},
  {name: 'Dotted eighth + sixteenth', time: '4/4', rhythm: 'e. s q h', expect: '1^(e &) a 2 3^(4)'},
  {name: 'Triplets', time: '4/4', rhythm: '[e e e] [e e e] q q', expect: '1 la le 2 la le 3 4'},
  {name: 'Triplet with a rest', time: '4/4', rhythm: '[e er e] q h', expect: '1 (la) le 2 3^(4)'},
  {name: 'Triplet quarter + eighth', time: '4/4', rhythm: '[q e] [q e] h', expect: '1^(la) le 2^(la) le 3^(4)'},
  {name: 'Tie within a measure', time: '4/4', rhythm: 'q_ q q q', expect: '1^(2) 3 4'},
  {name: 'Quarter tied to an eighth', time: '4/4', rhythm: 'q_ e e q q', expect: '1^(& 2) & 3 4'},
  {name: 'Tie across the bar line', time: '4/4', rhythm: 'q q h_ | q q h', expect: '1 2 3^(4 1) 2 3^(4)'},
  {name: 'Eighth tied across the bar line', time: '4/4', rhythm: 'q q q. e_ | e e q h', expect: '1 2 3^(& 4) &^(1) & 2 3^(4)'},
  {name: 'Whole note tied over', time: '4/4', rhythm: 'w_ | h h', expect: '1^(2 3 4 1 2) 3^(4)'},
  {name: '3/4 quarter notes', time: '3/4', rhythm: 'q q q', expect: '1 2 3'},
  {name: '3/4 dotted half', time: '3/4', rhythm: 'h.', expect: '1^(2 3)'},
  {name: '3/4 half + quarter', time: '3/4', rhythm: 'h q | q h', expect: '1^(2) 3 1 2^(3)'},
  {name: '3/4 rests', time: '3/4', rhythm: 'qr q q | hr q', expect: '(1) 2 3 (1^(2)) 3'},
  {name: '3/4 eighths', time: '3/4', rhythm: 'e e e e q', expect: '1 & 2 & 3'},
  {name: '2/4 quarters and a half', time: '2/4', rhythm: 'q q | h', expect: '1 2 1^(2)'},
  {name: '2/4 dotted quarter + eighth', time: '2/4', rhythm: 'e e q | q. e', expect: '1 & 2 1^(& 2) &'},
  {name: '6/8 eighths', time: '6/8', rhythm: 'e e e e e e', expect: '1 2 3 4 5 6'},
  {name: '6/8 dotted quarters', time: '6/8', rhythm: 'q. q.', expect: '1^(2 3) 4^(5 6)'},
  {name: '6/8 quarter + eighth', time: '6/8', rhythm: 'q e q e', expect: '1^(2) 3 4^(5) 6'},
  {name: '6/8 dotted half', time: '6/8', rhythm: 'h.', expect: '1^(2 3 4 5 6)'},
  {name: '6/8 sixteenths', time: '6/8', rhythm: 's s s s s s q.', expect: '1 & 2 & 3 & 4^(5 6)'},
  {name: '6/8 eighth rest', time: '6/8', rhythm: 'er e e q.', expect: '(1) 2 3 4^(5 6)'},
  {name: '6/8 dotted quarter rest', time: '6/8', rhythm: 'q.r e e e', expect: '(1^(2 3)) 4 5 6'},
  {name: '6/8 tie across the bar line', time: '6/8', rhythm: 'q. q._ | q. q.', expect: '1^(2 3) 4^(5 6 1 2 3) 4^(5 6)'},
];
